# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-26 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0092_remove_volunteer_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReimbursementEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Beløb')),
            ],
        ),
        migrations.CreateModel(
            name='ReimbursementEntryTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Kode')),
                ('title', models.CharField(max_length=20, verbose_name='Type')),
                ('description', models.TextField(verbose_name='Beskrivelse')),
            ],
        ),
        migrations.CreateModel(
            name='ReimbursementReciept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='Receipts')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Beløb')),
                ('merchant', models.CharField(max_length=60, verbose_name='Købsted')),
            ],
        ),
        migrations.CreateModel(
            name='ReimbursementRequestXena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_dtm', models.DateField(blank=True, null=True, verbose_name='Sendt til XENA')),
            ],
        ),
        migrations.CreateModel(
            name='ReimburseRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Titel')),
                ('validated_person_1_dtm', models.DateField(blank=True, null=True, verbose_name='Første godkendelse')),
                ('validated_person_2_dtm', models.DateField(blank=True, null=True, verbose_name='Anden godkendelse')),
                ('created_dtm', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Oprettet')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='Kommentar')),
                ('bank_message_reciever', models.CharField(max_length=60, verbose_name='Bank besked til modtager')),
                ('bank_message_sender', models.CharField(max_length=60, verbose_name='Bank besked til afsender')),
                ('bank_registration', models.CharField(blank=True, default='', max_length=4, verbose_name='Bank registreringsnummer')),
                ('bank_account', models.CharField(blank=True, default='', max_length=20, verbose_name='Bank kontonummer')),
                ('refunded_failed_dtm', models.DateField(blank=True, null=True, verbose_name='Fejlet')),
                ('refunded_failed_status', models.TextField(blank=True, null=True, verbose_name='Fejlbesked')),
                ('rejected_dtm', models.DateField(blank=True, null=True, verbose_name='Fejlet')),
                ('rejected_status', models.TextField(blank=True, null=True, verbose_name='Fejlbesked')),
                ('sent_dtm', models.DateField(blank=True, null=True, verbose_name='Sendt til bank')),
                ('refunded_dtm', models.DateField(blank=True, null=True, verbose_name='Refunderet')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Department')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimburse_request_receiver', to='members.Person')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimburse_request_submitter', to='members.Person')),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Union')),
                ('validated_person_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimburse_request_validated_person_1', to='members.Person')),
                ('validated_person_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimburse_request_validated_person_2', to='members.Person')),
            ],
        ),
        migrations.AddField(
            model_name='reimbursementrequestxena',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.ReimburseRequest'),
        ),
        migrations.AddField(
            model_name='reimbursementreciept',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.ReimburseRequest'),
        ),
        migrations.AddField(
            model_name='reimbursemententry',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.ReimburseRequest'),
        ),
        migrations.AddField(
            model_name='reimbursemententry',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.ReimbursementEntryTypes'),
        ),
    ]
